export const PROFILES = {
  SET_IS_FETCHING: 'SET_IS_FETCHING',
  SET_PROFILES: 'SET_PROFILES',
  SET_HAS_FETCHED_DATA: 'SET_HAS_FETCHED_DATA',
  SORT_ASCENDING: 'SORT_ASCENDING',
  SORT_DESCENDING: 'SORT_DESCENDING',
};
